// @flow
import createSymbol from 'lib/core/createSymbol';

const createInvitationSymbol = createSymbol('INVITATIONS');

export default {
  CREATE_INVITATION: createInvitationSymbol('CREATE_INVITATION'),
  SET_CREATE_INVITATION_FAILURE: createInvitationSymbol('SET_CREATE_INVITATION_FAILURE'),
  SET_CREATE_INVITATION_SUCCESS: createInvitationSymbol('SET_CREATE_INVITATION_SUCCESS'),

  GET_ALL_INVITATIONS: createInvitationSymbol('GET_ALL_INVITATIONS'),
  SET_GET_ALL_INVITATIONS_SUCCESS: createInvitationSymbol('SET_GET_ALL_INVITATIONS_SUCCESS'),
  SET_GET_ALL_INVITATIONS_FAILURE: createInvitationSymbol('SET_GET_ALL_INVITATIONS_FAILURE'),

  RESET_INVITATIONS_CREATE_STATE: createInvitationSymbol('RESET_INVITATIONS_CREATE_STATE'),
  RESET_GET_ALL_INVITATIONS_STATE: createInvitationSymbol('RESET_GET_ALL_INVITATIONS_STATE')
};
